### PR TITLE
I added the changes for the voting stuff.

### PR DESCRIPTION
**Pull request by candywal**

### CODE REVIEW

**Comment by caseyavila** [comment]
Is it possible to do this with image links rather than the images

**Comment by candywal** [comment]
You can just change source to a URL. Just had local images since didn't have URLs.

**Review by grant-baer — COMMENTED** [review]
LGTM

**Comment by candywal** [comment]
@Gannon44 can you review the changes here?

**Comment by Gannon44** [comment]
everything works on my end. lgtm

**Pull request merged**
