### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by nnayk**
Initial completion of end-to-end registration experience, starting with completion of the frontend form and ending with writing to the DB.

Note: The backend and frontend will need some changes once session tokens for a customized experience are implemented successfully. Currently, the registration page routes to the portfolio page but since the session tokens are not implemented there's no way to track a user's session state.

### CODE REVIEW

**Review by candywal — APPROVED** [review]
Changes look good, eventually we would want to change the registration page to redirect to the login page. We can do this when we work on the login + session token feature. PR LGTM.

**Comment by caseyavila** [comment]
lgtm

**Review by caseyavila — APPROVED** [review]

**Comment by nnayk** [comment]
> Changes look good, eventually we would want to change the registration page to redirect to the login page. We can do this when we work on the login + session token feature. PR LGTM.

Just discussed this with Gannon and Grant and they were also in favor of routing to login upon completion of registration. Added this change.

**Comment by Gannon44** [comment]
Everything works well on my end. Great job, lgtm

**Review by Gannon44 — COMMENTED** [review]
merged before i approved... sorry

**Pull request merged**
